spring:
  datasource:
    url:
      jdbc:mysql://db:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true
      &characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB